#include "ggml-metal-tuning.h"

#include <cstddef>
#include <cstring>
#include <iterator>

namespace ggml_metal_tuning {

int mm_tile_K_bucket(int64_t K) {
    for (int i = 0; i < (int) std::size(MM_TILE_K_BUCKETS); ++i) {
        if (K < MM_TILE_K_BUCKETS[i]) { return i; }
    }
    return (int) std::size(MM_TILE_K_BUCKETS);
}

int mm_tile_token_bucket(int64_t tokens) {
    for (int i = 0; i < (int) std::size(MM_TILE_TOKEN_BUCKETS); ++i) {
        if (tokens < MM_TILE_TOKEN_BUCKETS[i]) { return i; }
    }
    return (int) std::size(MM_TILE_TOKEN_BUCKETS);
}

mm_tile_cfg_t mm_tile_baseline_cfg() {
    return { 64, 32 };
}

// Generated by `test-backend-ops tune --tune-perf` on M4 Max; do not hand-edit.
// One row per kept bucket, plus per-(dtype) K-collapsed domain defaults
// (K_b = MM_TILE_NR_DEFAULT, tokens_b = domain). See ggml-metal-tuning.h.
constexpr mm_tile_entry_t mm_tile_tuned_table[] = {
    // ---- q4_0 ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, -1, 1, {0,0,0,0} }, { 32,  8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0,  1, 2, {0,0,0,0} }, { 32, 16 } },
    // ---- q8_0 ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, -1, 1, {0,0,0,0} }, { 32,  8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0,  1, 2, {0,0,0,0} }, { 32, 16 } },
    // ---- q4_K ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, -1, 1, {0,0,0,0} }, { 32, 16 } },
    // ---- f16 ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16,  -1, 1, {0,0,0,0} }, { 32,  8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16,   1, 2, {0,0,0,0} }, { 64, 16 } },
};

static enum ggml_metal_device_id mm_tile_family_representative(int gpu_family) {
    switch (gpu_family) {
        case 9:  return GGML_METAL_DEVICE_M4_MAX;
        default: return GGML_METAL_DEVICE_GENERIC;
    }
}

static bool         g_mm_override_set = false;
static mm_tile_cfg_t g_mm_override_cfg = { 64, 32 };

void mm_tile_set_override(mm_tile_cfg_t cfg) {
    g_mm_override_cfg = cfg;
    g_mm_override_set = true;
}

void mm_tile_clear_override() {
    g_mm_override_set = false;
}

bool mm_tile_override_active() {
    return g_mm_override_set;
}

static const mm_tile_cfg_t * find_cfg(const mm_tile_entry_t * tbl, size_t n, const mm_tile_key_t & k) {
    for (size_t i = 0; i < n; ++i) {
        if (memcmp(&tbl[i].key, &k, sizeof(k)) == 0) { return &tbl[i].cfg; }
    }
    return nullptr;
}

mm_tile_cfg_t mm_tile_pick(enum ggml_metal_device_id device_id,
                            int gpu_family,
                            int dtype,
                            int64_t K,
                            int64_t tokens) {
    if (g_mm_override_set) { return g_mm_override_cfg; }

    const mm_tile_cfg_t baseline = mm_tile_baseline_cfg();
    const int K_b      = mm_tile_K_bucket(K);
    const int tokens_b = mm_tile_token_bucket(tokens);

    mm_tile_key_t k{};
    k.dtype    = (int8_t) dtype;

    auto lookup = [&](enum ggml_metal_device_id dev) -> const mm_tile_cfg_t * {
        k.device_id = (int8_t) dev;
        k.K_b       = (int8_t) K_b;
        k.tokens_b  = (int8_t) tokens_b;
        if (auto * c = find_cfg(mm_tile_tuned_table, std::size(mm_tile_tuned_table), k)) {
            return c;
        }
        k.K_b      = MM_TILE_NR_DEFAULT;
        k.tokens_b = (tokens_b == 0) ? MM_TILE_DOMAIN_DECODE : MM_TILE_DOMAIN_BATCH;
        return find_cfg(mm_tile_tuned_table, std::size(mm_tile_tuned_table), k);
    };

    if (auto * c = lookup(device_id)) { return *c; }

    if (gpu_family > 0) {
        const enum ggml_metal_device_id rep = mm_tile_family_representative(gpu_family);
        if (rep != GGML_METAL_DEVICE_GENERIC) {
            if (auto * c = lookup(rep)) { return *c; }
        }
    }
    return baseline;
}

}  // namespace ggml_metal_tuning
