#include "ggml-metal-tuning.h"

#include <cstddef>
#include <cstring>
#include <iterator>

namespace ggml_metal_tuning {

int mm_tile_K_bucket(int64_t K) {
    for (int i = 0; i < (int) std::size(MM_TILE_K_BUCKETS); ++i) {
        if (K < MM_TILE_K_BUCKETS[i]) { return i; }
    }
    return (int) std::size(MM_TILE_K_BUCKETS);
}

int mm_tile_N0_bucket(int64_t N_out) {
    for (int i = 0; i < (int) std::size(MM_TILE_N0_BUCKETS); ++i) {
        if (N_out < MM_TILE_N0_BUCKETS[i]) { return i; }
    }
    return (int) std::size(MM_TILE_N0_BUCKETS);
}

int mm_tile_token_bucket(int64_t tokens) {
    for (int i = 0; i < (int) std::size(MM_TILE_TOKEN_BUCKETS); ++i) {
        if (tokens < MM_TILE_TOKEN_BUCKETS[i]) { return i; }
    }
    return (int) std::size(MM_TILE_TOKEN_BUCKETS);
}

mm_tile_cfg_t mm_tile_baseline_cfg() {
    return MM_TILE_BASELINE_CFG;
}

// Tuned tile table. Generated by `test-backend-ops tune -b MTL0 --tune-perf` on
// Apple M4 Max (Apple9, has_tensor=false), 2026-07-22; raw sweep in
// docs/mm-tile-sweep-m4max-20260722-P5-floor.txt. Regenerate on new hardware
// and paste; do NOT hand-edit rows.
//
// Rows are emitted by group_split (min-max-regret over the shape-zoo) in two kinds:
//   - L2b default: (K_b=ANY, N0_b=ANY, tokens_b) — the token bucket's fallback tile.
//   - L1 exact:    (K_b, N0_b, tokens_b) — a specific (K,N0) cell whose winner
//                  differs from the bucket default (incl. pinning back to baseline).
// Every emitted tile clears a real-token floor: it must not lose to baseline by >2%
// at any real prefill token in its cell (see run_mm_tile_tune_perf), so an unsampled
// cell falls through to baseline rather than inheriting an off-ladder-only win.
// Key layout {device_id, dtype, K_b, N0_b, tokens_b}; see ggml-metal-tuning.h for
// bucket edges. Keyed to M4_MAX; any Apple9 SKU resolves here via the family rep,
// other devices fall through to baseline. The top token bucket [256,inf) has no
// rows: {256,512,2048} all measured baseline, so prefill stays on kernel_mul_mm.
constexpr mm_tile_entry_t mm_tile_tuned_table[] = {
    // ---- q4_0: 22 rows ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, -1, -1, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 4, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 2, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 0, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 2, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 2, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 2, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 3, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 0, 0, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 2, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 1, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 1, 0, 3, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_0, 3, 0, 3, {0,0,0} }, { 32, 16 } },
    // ---- q8_0: 21 rows ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, -1, -1, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 4, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 2, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 3, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 0, 0, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 2, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 2, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 2, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 3, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 3, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 3, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 3, 3, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 0, 0, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 2, 0, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 3, 0, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q8_0, 1, 0, 3, {0,0,0} }, { 32, 16 } },
    // ---- q4_K: 21 rows ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, -1, -1, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 2, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 4, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 2, 2, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 2, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 3, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 0, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 2, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 2, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 2, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 3, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 3, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 3, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 3, 3, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 0, 0, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 3, 0, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_Q4_K, 1, 0, 3, {0,0,0} }, { 32, 16 } },
    // ---- f16: 27 rows ----
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 0, 0, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 0, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 1, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 2, 0, {0,0,0} }, { 64, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 3, 0, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 2, 0, 0, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 2, 2, 0, {0,0,0} }, { 64, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 0, 0, {0,0,0} }, { 64, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 2, 0, {0,0,0} }, { 64, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 0, 0, 1, {0,0,0} }, { 64, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 1, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 2, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 2, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 0, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 1, 1, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 2, 1, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 0, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 1, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 2, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 0, 2, {0,0,0} }, { 32, 8 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 3, 1, 2, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 0, 0, 3, {0,0,0} }, { 64, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 1, 0, 3, {0,0,0} }, { 32, 16 } },
    { { GGML_METAL_DEVICE_M4_MAX, GGML_TYPE_F16, 2, 0, 3, {0,0,0} }, { 32, 16 } },
};

// Compile-time: every tuned-table row must be a family member or the baseline.
static constexpr bool mm_tile_cfg_in_family(int16_t nr0, int16_t nr1) {
    if (nr0 == MM_TILE_BASELINE_CFG.nr0 && nr1 == MM_TILE_BASELINE_CFG.nr1) { return true; }
    for (const auto & f : MM_TILE_FAMILY) {
        if (f.nr0 == nr0 && f.nr1 == nr1) { return true; }
    }
    return false;
}

static constexpr bool mm_tile_table_all_legal() {
    for (const auto & e : mm_tile_tuned_table) {
        if (!mm_tile_cfg_in_family(e.cfg.nr0, e.cfg.nr1)) { return false; }
    }
    return true;
}

static_assert(mm_tile_table_all_legal(), "mm_tile_tuned_table row uses an illegal (nr0,nr1)");

// Map a device SKU to its Apple GPU family, then to that family's representative
// SKU (the one we have tuned data for). Apple GPU family is a static property of
// the SKU: M1->Apple7, M2->Apple8, M3/M4/M5->Apple9. Used as the device-level
// fallback when the exact device_id has no tuned rows.
static int mm_tile_gpu_family(enum ggml_metal_device_id device_id) {
    switch (device_id) {
        case GGML_METAL_DEVICE_M1:
        case GGML_METAL_DEVICE_M1_PRO:
        case GGML_METAL_DEVICE_M1_MAX:
        case GGML_METAL_DEVICE_M1_ULTRA:
            return 7;
        case GGML_METAL_DEVICE_M2:
        case GGML_METAL_DEVICE_M2_PRO:
        case GGML_METAL_DEVICE_M2_MAX:
        case GGML_METAL_DEVICE_M2_ULTRA:
            return 8;
        case GGML_METAL_DEVICE_M3:
        case GGML_METAL_DEVICE_M3_PRO:
        case GGML_METAL_DEVICE_M3_MAX:
        case GGML_METAL_DEVICE_M3_ULTRA:
        case GGML_METAL_DEVICE_M4:
        case GGML_METAL_DEVICE_M4_PRO:
        case GGML_METAL_DEVICE_M4_MAX:
        case GGML_METAL_DEVICE_M5:
        case GGML_METAL_DEVICE_M5_PRO:
        case GGML_METAL_DEVICE_M5_MAX:
        case GGML_METAL_DEVICE_M5_ULTRA:
            return 9;
        default:
            return 0;
    }
}

static enum ggml_metal_device_id mm_tile_family_representative(enum ggml_metal_device_id device_id) {
    switch (mm_tile_gpu_family(device_id)) {
        case 9:  return GGML_METAL_DEVICE_M4_MAX;  // only Apple9 has tuned data
        default: return GGML_METAL_DEVICE_GENERIC;
    }
}

static bool         g_mm_override_set = false;
static mm_tile_cfg_t g_mm_override_cfg = { 64, 32 };

void mm_tile_set_override(mm_tile_cfg_t cfg) {
    g_mm_override_cfg = cfg;
    g_mm_override_set = true;
}

void mm_tile_clear_override() {
    g_mm_override_set = false;
}

bool mm_tile_override_active() {
    return g_mm_override_set;
}

static const mm_tile_cfg_t * find_cfg(const mm_tile_entry_t * tbl, size_t n, const mm_tile_key_t & k) {
    for (size_t i = 0; i < n; ++i) {
        if (memcmp(&tbl[i].key, &k, sizeof(k)) == 0) { return &tbl[i].cfg; }
    }
    return nullptr;
}

// Core lattice lookup against an explicit table. mm_tile_pick and the self-test
// share this so both exercise the same collapse logic. Folding order is weakest
// signal first and tokens is never folded:
//   L1 exact  (K_b,  N0_b, tokens_b)
//   L2a       (ANY,  N0_b, tokens_b)   collapse K, keep out-feat + tokens
//   L2b       (ANY,  ANY,  tokens_b)   out-feat also missing, keep tokens
//   L3        baseline (64x32)         nothing matched
// The device axis wraps the lattice: exact device_id -> family rep -> baseline.
static mm_tile_cfg_t mm_tile_pick_from_table(const mm_tile_entry_t * tbl, size_t n,
                                             enum ggml_metal_device_id device_id,
                                             int dtype, int64_t K, int64_t N_out, int64_t tokens) {
    const int K_b      = mm_tile_K_bucket(K);
    const int N0_b     = mm_tile_N0_bucket(N_out);
    const int tokens_b = mm_tile_token_bucket(tokens);

    mm_tile_key_t k{};
    k.dtype    = (int8_t) dtype;
    k.tokens_b = (int8_t) tokens_b;  // never collapsed; set once

    // L1/L2a/L2b each reassign K_b and N0_b (k is reused across levels, so a
    // stale field left over from the previous level would poison the memcmp).
    auto lookup = [&](enum ggml_metal_device_id dev) -> const mm_tile_cfg_t * {
        k.device_id = (int8_t) dev;
        k.K_b = (int8_t) K_b;       k.N0_b = (int8_t) N0_b;      // L1
        if (auto * c = find_cfg(tbl, n, k)) { return c; }
        k.K_b = MM_TILE_BUCKET_ANY; k.N0_b = (int8_t) N0_b;      // L2a
        if (auto * c = find_cfg(tbl, n, k)) { return c; }
        k.K_b = MM_TILE_BUCKET_ANY; k.N0_b = MM_TILE_BUCKET_ANY; // L2b
        return find_cfg(tbl, n, k);
    };

    // exact device_id -> family representative SKU -> baseline
    if (auto * c = lookup(device_id)) { return *c; }

    const enum ggml_metal_device_id rep = mm_tile_family_representative(device_id);
    if (rep != GGML_METAL_DEVICE_GENERIC && rep != device_id) {
        if (auto * c = lookup(rep)) { return *c; }
    }
    return mm_tile_baseline_cfg();  // L3
}

mm_tile_cfg_t mm_tile_pick(enum ggml_metal_device_id device_id,
                            int dtype,
                            int64_t K,
                            int64_t N_out,
                            int64_t tokens) {
    if (g_mm_override_set) { return g_mm_override_cfg; }

    // Large-batch short-circuit: every tuned device converged to baseline for
    // tokens >= 256 (the top token bucket has no rows by design), and at these
    // sizes the baseline dispatch always saturates the GPU. Skip the scan.
    if (tokens >= 256) { return mm_tile_baseline_cfg(); }

    const mm_tile_cfg_t cfg = mm_tile_pick_from_table(mm_tile_tuned_table, std::size(mm_tile_tuned_table),
                                                      device_id, dtype, K, N_out, tokens);

    // Occupancy veto (see MM_TILE_C_SAT_M4_MAX): if the baseline dispatch
    // already saturates the GPU, a smaller tile cannot win, so override any
    // small-tile row back to baseline. Guards against table extrapolation on
    // unsampled shapes. tokens < 32 wins are padding-driven, not occupancy
    // -driven, and stay exempt.
    if (tokens >= 32 &&
        (cfg.nr0 != MM_TILE_BASELINE_CFG.nr0 || cfg.nr1 != MM_TILE_BASELINE_CFG.nr1)) {
        const int64_t n_tg = ((N_out + 63) / 64) * ((tokens + 31) / 32);
        if (n_tg >= MM_TILE_C_SAT_M4_MAX) {
            return mm_tile_baseline_cfg();
        }
    }
    return cfg;
}

int mm_tile_lattice_selftest() {
    // Synthetic table keyed to one device so the device axis is a no-op and the
    // (K_b, N0_b) collapse is isolated. All rows share tokens_b=1 (tokens never
    // folds); queries land in the buckets noted inline.
    constexpr enum ggml_metal_device_id dev = GGML_METAL_DEVICE_M4_MAX;
    constexpr int                       dt  = GGML_TYPE_Q4_0;
    constexpr mm_tile_cfg_t exact_cfg = { 128, 32 };
    constexpr mm_tile_cfg_t l2a_cfg   = {  64, 16 };
    constexpr mm_tile_cfg_t l2b_cfg   = {  32,  8 };
    const mm_tile_entry_t tbl[] = {
        { { dev, dt, 1, 1, 1, {0,0,0} }, exact_cfg },  // L1: K_b=1, N0_b=1, tokens_b=1
        { { dev, dt, MM_TILE_BUCKET_ANY, 1, 1, {0,0,0} }, l2a_cfg },  // L2a: keep N0_b=1, tokens_b=1
        { { dev, dt, MM_TILE_BUCKET_ANY, MM_TILE_BUCKET_ANY, 1, {0,0,0} }, l2b_cfg },  // L2b: tokens_b=1
    };
    const size_t        n    = std::size(tbl);
    const mm_tile_cfg_t base = mm_tile_baseline_cfg();

    auto eq = [](mm_tile_cfg_t a, mm_tile_cfg_t b) { return a.nr0 == b.nr0 && a.nr1 == b.nr1; };
    // Bucket edges: K_b {2048,8192,16384}, N0_b {2048,4608,8192,30000}, tokens_b {32,64,128}.
    int fails = 0;
    // L1 hit: K_b=1 (4096), N0_b=1 (4096), tokens_b=1 (48)
    if (!eq(mm_tile_pick_from_table(tbl, n, dev, dt, 4096, 4096, 48), exact_cfg)) { fails++; }
    // L1 miss, L2a hit: K_b=0 (1024, no exact row), N0_b=1 (4096), tokens_b=1 (48)
    if (!eq(mm_tile_pick_from_table(tbl, n, dev, dt, 1024, 4096, 48), l2a_cfg))   { fails++; }
    // L1+L2a miss, L2b hit: N0_b=0 (512, no L2a row keeps it), tokens_b=1 (48)
    if (!eq(mm_tile_pick_from_table(tbl, n, dev, dt, 1024,  512, 48), l2b_cfg))   { fails++; }
    // all miss -> baseline: tokens_b=0 (8) matches no row
    if (!eq(mm_tile_pick_from_table(tbl, n, dev, dt, 1024,  512,  8), base))      { fails++; }
    // tokens never folds: (K_b=1,N0_b=1) would hit L1 if tokens folded, but
    // tokens_b=3 (256) matches no row at any level -> baseline
    if (!eq(mm_tile_pick_from_table(tbl, n, dev, dt, 4096, 4096, 256), base))     { fails++; }
    return fails;
}

}  // namespace ggml_metal_tuning
